### ISSUE TITLE
container not building 'No module named 'distutils.msvccompiler''

### ISSUE THREAD

**Issue by mat-ole** [tikk3r/lofar-grid-hpccloud#90] opened 2024-09-03 10:06 UTC
Currently building the container returns an error during compilation of RMextract:

`ModuleNotFoundError: No module named 'distutils.msvccompiler'`

It happened after release of setuptools v74.0.0  where they removed some depreciated functions of distutils. Probably it doesn't work well with 1.26.2 version of numpy required in the script.

forcing
`pip install "setuptools=73.0.1"`
fixes the problem

**Comment by tikk3r** [comment] 2024-09-06 13:59
I think the cause was the `RMextract` version that was a bit old. It should be fixed now.

**Closed as completed by tikk3r** 2024-09-06 13:59 UTC
Labels: bug
